version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
#      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD:
#      MYSQL_DATABASE: order_service
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql