version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
#      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: mysql
#      MYSQL_DATABASE: order_service
    volumes:
      - ./mysql:/var/lib/mysql
